consumes:
- application/json
info:
  description: Hardener appliacnation
  title: Hardener Application
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  createjob:
    type: object
    required:
      - hostname
      - username
      - password
    properties:
      id:
        type: string
        minLength: 1
      hostname:
        type: string
        minLength: 1
      username:
        type: string
        minLength: 1
      password:
        type: string
        minLength: 1
  getjob:
    type: object
    properties:
      id:
        type: string
      hostname:
        type: string
      progress:
        type: integer
        format: int64
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /:
    post:
      tags:
        - hardener
      operationId: create
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createjob"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/createjob"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      tags:
        - hardener
      responses:
        200:
          description: job progress
          schema:
            $ref: "#/definitions/getjob"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

          



